[manager]
prepend_keymap = [
  { on = [ "g", "h" ], run = "cd ~", desc = "Go home" },
  { on = [ "g", "d" ], run = "cd ~/Downloads", desc = "Go downloads" },
  { on = [ "g", "n" ], run = "cd ~/nixos-conf", desc = "Go nixos-conf" },
  { on = [ "g", "c" ], run = "cd ~/.config", desc = "Go config" },
  { on = [ "Y" ], run = "yank", desc = "Yank file/dir" },
]
