profile=gpu-hq
hwdec=vaapi
vo=gpu-next
gpu-context=wayland
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
video-sync=display-resample
interpolation
tscale=oversample
demuxer-max-bytes=500M
demuxer-max-back-bytes=100M
cache=yes
cache-secs=300
keep-open=yes
save-position-on-quit=yes
volume-max=200
volume-normalize=yes
audio-file-auto=fuzzy
sub-auto=fuzzy
