color_theme = "gruvbox_dark"
theme_background = false
graph_symbol_cpu = "braille"
graph_symbol_mem = "braille"
graph_symbol_net = "braille"
graph_symbol_proc = "default"
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_reversed = true
proc_gradient = true
proc_per_core = true
proc_tree = false
temp_show = "cpu"
